package com.elefirst.system.po;

import com.elefirst.base.entity.Page;

import java.util.Date;

public class AreaInfo extends Page {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.id
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.area_id
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String areaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.name
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.abbreviation
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String abbreviation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.icp
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String icp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.establishment_date
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private Date establishmentDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.registered_capital
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String registeredCapital;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.number_of_employees
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String numberOfEmployees;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.stock_code
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String stockCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.area
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.contract_capacity
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String contractCapacity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.operation_capacity
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String operationCapacity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.account_number
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String accountNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.voltage_level
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String voltageLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.executive_name
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String executiveName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.executive_tel
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String executiveTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.person_in_charge_name
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String personInChargeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.person_in_charge_tel
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String personInChargeTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.create_person
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String createPerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.create_date
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.update_person
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private String updatePerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_200_area_info.update_date
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	private Date updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.id
	 *
	 * @return the value of t_200_area_info.id
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.id
	 *
	 * @param id the value for t_200_area_info.id
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.area_id
	 *
	 * @return the value of t_200_area_info.area_id
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getAreaId() {
		return areaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.area_id
	 * @param areaId  the value for t_200_area_info.area_id
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setAreaId(String areaId) {
		this.areaId = areaId == null ? null : areaId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.name
	 * @return the value of t_200_area_info.name
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.name
	 *
	 * @param name the value for t_200_area_info.name
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.abbreviation
	 *
	 * @return the value of t_200_area_info.abbreviation
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getAbbreviation() {
		return abbreviation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.abbreviation
	 *
	 * @param abbreviation the value for t_200_area_info.abbreviation
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation == null ? null : abbreviation.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.icp
	 *
	 * @return the value of t_200_area_info.icp
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getIcp() {
		return icp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.icp
	 *
	 * @param icp the value for t_200_area_info.icp
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setIcp(String icp) {
		this.icp = icp == null ? null : icp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.establishment_date
	 *
	 * @return the value of t_200_area_info.establishment_date
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public Date getEstablishmentDate() {
		return establishmentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.establishment_date
	 *
	 * @param establishmentDate the value for t_200_area_info.establishment_date
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setEstablishmentDate(Date establishmentDate) {
		this.establishmentDate = establishmentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.registered_capital
	 *
	 * @return the value of t_200_area_info.registered_capital
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getRegisteredCapital() {
		return registeredCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.registered_capital
	 *
	 * @param registeredCapital the value for t_200_area_info.registered_capital
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setRegisteredCapital(String registeredCapital) {
		this.registeredCapital = registeredCapital == null ? null : registeredCapital.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.number_of_employees
	 *
	 * @return the value of t_200_area_info.number_of_employees
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getNumberOfEmployees() {
		return numberOfEmployees;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.number_of_employees
	 *
	 * @param numberOfEmployees the value for t_200_area_info.number_of_employees
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setNumberOfEmployees(String numberOfEmployees) {
		this.numberOfEmployees = numberOfEmployees == null ? null : numberOfEmployees.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.stock_code
	 *
	 * @return the value of t_200_area_info.stock_code
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getStockCode() {
		return stockCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.stock_code
	 *
	 * @param stockCode the value for t_200_area_info.stock_code
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setStockCode(String stockCode) {
		this.stockCode = stockCode == null ? null : stockCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.area
	 *
	 * @return the value of t_200_area_info.area
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.area
	 *
	 * @param area the value for t_200_area_info.area
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setArea(String area) {
		this.area = area == null ? null : area.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.contract_capacity
	 *
	 * @return the value of t_200_area_info.contract_capacity
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getContractCapacity() {
		return contractCapacity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.contract_capacity
	 *
	 * @param contractCapacity the value for t_200_area_info.contract_capacity
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setContractCapacity(String contractCapacity) {
		this.contractCapacity = contractCapacity == null ? null : contractCapacity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.operation_capacity
	 *
	 * @return the value of t_200_area_info.operation_capacity
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getOperationCapacity() {
		return operationCapacity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.operation_capacity
	 *
	 * @param operationCapacity the value for t_200_area_info.operation_capacity
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setOperationCapacity(String operationCapacity) {
		this.operationCapacity = operationCapacity == null ? null : operationCapacity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.account_number
	 *
	 * @return the value of t_200_area_info.account_number
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getAccountNumber() {
		return accountNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.account_number
	 *
	 * @param accountNumber the value for t_200_area_info.account_number
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber == null ? null : accountNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.voltage_level
	 *
	 * @return the value of t_200_area_info.voltage_level
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getVoltageLevel() {
		return voltageLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.voltage_level
	 *
	 * @param voltageLevel the value for t_200_area_info.voltage_level
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setVoltageLevel(String voltageLevel) {
		this.voltageLevel = voltageLevel == null ? null : voltageLevel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.executive_name
	 *
	 * @return the value of t_200_area_info.executive_name
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getExecutiveName() {
		return executiveName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.executive_name
	 *
	 * @param executiveName the value for t_200_area_info.executive_name
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setExecutiveName(String executiveName) {
		this.executiveName = executiveName == null ? null : executiveName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.executive_tel
	 *
	 * @return the value of t_200_area_info.executive_tel
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getExecutiveTel() {
		return executiveTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.executive_tel
	 *
	 * @param executiveTel the value for t_200_area_info.executive_tel
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setExecutiveTel(String executiveTel) {
		this.executiveTel = executiveTel == null ? null : executiveTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.person_in_charge_name
	 *
	 * @return the value of t_200_area_info.person_in_charge_name
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getPersonInChargeName() {
		return personInChargeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.person_in_charge_name
	 *
	 * @param personInChargeName the value for t_200_area_info.person_in_charge_name
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setPersonInChargeName(String personInChargeName) {
		this.personInChargeName = personInChargeName == null ? null : personInChargeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.person_in_charge_tel
	 *
	 * @return the value of t_200_area_info.person_in_charge_tel
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getPersonInChargeTel() {
		return personInChargeTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.person_in_charge_tel
	 *
	 * @param personInChargeTel the value for t_200_area_info.person_in_charge_tel
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setPersonInChargeTel(String personInChargeTel) {
		this.personInChargeTel = personInChargeTel == null ? null : personInChargeTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.create_person
	 * @return the value of t_200_area_info.create_person
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getCreatePerson() {
		return createPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.create_person
	 * @param createPerson  the value for t_200_area_info.create_person
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setCreatePerson(String createPerson) {
		this.createPerson = createPerson == null ? null : createPerson.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.create_date
	 * @return the value of t_200_area_info.create_date
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.create_date
	 * @param createDate  the value for t_200_area_info.create_date
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.update_person
	 * @return the value of t_200_area_info.update_person
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public String getUpdatePerson() {
		return updatePerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.update_person
	 * @param updatePerson  the value for t_200_area_info.update_person
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setUpdatePerson(String updatePerson) {
		this.updatePerson = updatePerson == null ? null : updatePerson.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_200_area_info.update_date
	 *
	 * @return the value of t_200_area_info.update_date
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_200_area_info.update_date
	 *
	 * @param updateDate the value for t_200_area_info.update_date
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		AreaInfo other = (AreaInfo) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getAreaId() == null ? other.getAreaId() == null : this.getAreaId().equals(other.getAreaId()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getAbbreviation() == null ? other.getAbbreviation() == null
				: this.getAbbreviation().equals(other.getAbbreviation()))
				&& (this.getIcp() == null ? other.getIcp() == null : this.getIcp().equals(other.getIcp()))
				&& (this.getEstablishmentDate() == null ? other.getEstablishmentDate() == null
				: this.getEstablishmentDate().equals(other.getEstablishmentDate()))
				&& (this.getRegisteredCapital() == null ? other.getRegisteredCapital() == null
				: this.getRegisteredCapital().equals(other.getRegisteredCapital()))
				&& (this.getNumberOfEmployees() == null ? other.getNumberOfEmployees() == null
				: this.getNumberOfEmployees().equals(other.getNumberOfEmployees()))
				&& (this.getStockCode() == null ? other.getStockCode() == null
				: this.getStockCode().equals(other.getStockCode()))
				&& (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
				&& (this.getContractCapacity() == null ? other.getContractCapacity() == null
				: this.getContractCapacity().equals(other.getContractCapacity()))
				&& (this.getOperationCapacity() == null ? other.getOperationCapacity() == null
				: this.getOperationCapacity().equals(other.getOperationCapacity()))
				&& (this.getAccountNumber() == null ? other.getAccountNumber() == null
				: this.getAccountNumber().equals(other.getAccountNumber()))
				&& (this.getVoltageLevel() == null ? other.getVoltageLevel() == null
				: this.getVoltageLevel().equals(other.getVoltageLevel()))
				&& (this.getExecutiveName() == null ? other.getExecutiveName() == null
				: this.getExecutiveName().equals(other.getExecutiveName()))
				&& (this.getExecutiveTel() == null ? other.getExecutiveTel() == null
				: this.getExecutiveTel().equals(other.getExecutiveTel()))
				&& (this.getPersonInChargeName() == null ? other.getPersonInChargeName() == null
				: this.getPersonInChargeName().equals(other.getPersonInChargeName()))
				&& (this.getPersonInChargeTel() == null ? other.getPersonInChargeTel() == null
				: this.getPersonInChargeTel().equals(other.getPersonInChargeTel()))
				&& (this.getCreatePerson() == null ? other.getCreatePerson() == null
				: this.getCreatePerson().equals(other.getCreatePerson()))
				&& (this.getCreateDate() == null ? other.getCreateDate() == null
				: this.getCreateDate().equals(other.getCreateDate()))
				&& (this.getUpdatePerson() == null ? other.getUpdatePerson() == null
				: this.getUpdatePerson().equals(other.getUpdatePerson()))
				&& (this.getUpdateDate() == null ? other.getUpdateDate() == null
				: this.getUpdateDate().equals(other.getUpdateDate()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getAbbreviation() == null) ? 0 : getAbbreviation().hashCode());
		result = prime * result + ((getIcp() == null) ? 0 : getIcp().hashCode());
		result = prime * result + ((getEstablishmentDate() == null) ? 0 : getEstablishmentDate().hashCode());
		result = prime * result + ((getRegisteredCapital() == null) ? 0 : getRegisteredCapital().hashCode());
		result = prime * result + ((getNumberOfEmployees() == null) ? 0 : getNumberOfEmployees().hashCode());
		result = prime * result + ((getStockCode() == null) ? 0 : getStockCode().hashCode());
		result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
		result = prime * result + ((getContractCapacity() == null) ? 0 : getContractCapacity().hashCode());
		result = prime * result + ((getOperationCapacity() == null) ? 0 : getOperationCapacity().hashCode());
		result = prime * result + ((getAccountNumber() == null) ? 0 : getAccountNumber().hashCode());
		result = prime * result + ((getVoltageLevel() == null) ? 0 : getVoltageLevel().hashCode());
		result = prime * result + ((getExecutiveName() == null) ? 0 : getExecutiveName().hashCode());
		result = prime * result + ((getExecutiveTel() == null) ? 0 : getExecutiveTel().hashCode());
		result = prime * result + ((getPersonInChargeName() == null) ? 0 : getPersonInChargeName().hashCode());
		result = prime * result + ((getPersonInChargeTel() == null) ? 0 : getPersonInChargeTel().hashCode());
		result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
		result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
		result = prime * result + ((getUpdatePerson() == null) ? 0 : getUpdatePerson().hashCode());
		result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
	 *
	 * @mbg.generated Thu Feb 09 16:57:56 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", areaId=").append(areaId);
		sb.append(", name=").append(name);
		sb.append(", abbreviation=").append(abbreviation);
		sb.append(", icp=").append(icp);
		sb.append(", establishmentDate=").append(establishmentDate);
		sb.append(", registeredCapital=").append(registeredCapital);
		sb.append(", numberOfEmployees=").append(numberOfEmployees);
		sb.append(", stockCode=").append(stockCode);
		sb.append(", area=").append(area);
		sb.append(", contractCapacity=").append(contractCapacity);
		sb.append(", operationCapacity=").append(operationCapacity);
		sb.append(", accountNumber=").append(accountNumber);
		sb.append(", voltageLevel=").append(voltageLevel);
		sb.append(", executiveName=").append(executiveName);
		sb.append(", executiveTel=").append(executiveTel);
		sb.append(", personInChargeName=").append(personInChargeName);
		sb.append(", personInChargeTel=").append(personInChargeTel);
		sb.append(", createPerson=").append(createPerson);
		sb.append(", createDate=").append(createDate);
		sb.append(", updatePerson=").append(updatePerson);
		sb.append(", updateDate=").append(updateDate);
		sb.append("]");
		return sb.toString();
	}
}