package com.elefirst.system.po;

import com.elefirst.base.entity.Page;

public class ConcentratorInfo extends Page {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_101_concentrator_info.id
     *
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_101_concentrator_info.area_id
     *
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_101_concentrator_info.concentrator_id
     *
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    private String concentratorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_101_concentrator_info.pn
     *
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    private String pn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_101_concentrator_info.name
     *
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_101_concentrator_info.pt
     *
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    private Double pt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_101_concentrator_info.ct
     *
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    private Double ct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_101_concentrator_info.display_order
     *
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    private Integer displayOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_101_concentrator_info.id
     *
     * @return the value of t_101_concentrator_info.id
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_101_concentrator_info.id
     *
     * @param id the value for t_101_concentrator_info.id
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_101_concentrator_info.area_id
     *
     * @return the value of t_101_concentrator_info.area_id
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_101_concentrator_info.area_id
     *
     * @param areaId the value for t_101_concentrator_info.area_id
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_101_concentrator_info.concentrator_id
     *
     * @return the value of t_101_concentrator_info.concentrator_id
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public String getConcentratorId() {
        return concentratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_101_concentrator_info.concentrator_id
     *
     * @param concentratorId the value for t_101_concentrator_info.concentrator_id
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public void setConcentratorId(String concentratorId) {
        this.concentratorId = concentratorId == null ? null : concentratorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_101_concentrator_info.pn
     *
     * @return the value of t_101_concentrator_info.pn
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public String getPn() {
        return pn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_101_concentrator_info.pn
     *
     * @param pn the value for t_101_concentrator_info.pn
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public void setPn(String pn) {
        this.pn = pn == null ? null : pn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_101_concentrator_info.name
     *
     * @return the value of t_101_concentrator_info.name
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_101_concentrator_info.name
     *
     * @param name the value for t_101_concentrator_info.name
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_101_concentrator_info.pt
     *
     * @return the value of t_101_concentrator_info.pt
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public Double getPt() {
        return pt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_101_concentrator_info.pt
     *
     * @param pt the value for t_101_concentrator_info.pt
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public void setPt(Double pt) {
        this.pt = pt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_101_concentrator_info.ct
     *
     * @return the value of t_101_concentrator_info.ct
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public Double getCt() {
        return ct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_101_concentrator_info.ct
     *
     * @param ct the value for t_101_concentrator_info.ct
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public void setCt(Double ct) {
        this.ct = ct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_101_concentrator_info.display_order
     *
     * @return the value of t_101_concentrator_info.display_order
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_101_concentrator_info.display_order
     *
     * @param displayOrder the value for t_101_concentrator_info.display_order
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_101_concentrator_info
     *
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ConcentratorInfo other = (ConcentratorInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getAreaId() == null ? other.getAreaId() == null : this.getAreaId().equals(other.getAreaId()))
                && (this.getConcentratorId() == null ? other.getConcentratorId() == null : this.getConcentratorId().equals(other.getConcentratorId()))
                && (this.getPn() == null ? other.getPn() == null : this.getPn().equals(other.getPn()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getPt() == null ? other.getPt() == null : this.getPt().equals(other.getPt()))
                && (this.getCt() == null ? other.getCt() == null : this.getCt().equals(other.getCt()))
                && (this.getDisplayOrder() == null ? other.getDisplayOrder() == null : this.getDisplayOrder().equals(other.getDisplayOrder()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_101_concentrator_info
     *
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
        result = prime * result + ((getConcentratorId() == null) ? 0 : getConcentratorId().hashCode());
        result = prime * result + ((getPn() == null) ? 0 : getPn().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPt() == null) ? 0 : getPt().hashCode());
        result = prime * result + ((getCt() == null) ? 0 : getCt().hashCode());
        result = prime * result + ((getDisplayOrder() == null) ? 0 : getDisplayOrder().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_101_concentrator_info
     *
     * @mbggenerated Sat Jan 28 23:53:42 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", areaId=").append(areaId);
        sb.append(", concentratorId=").append(concentratorId);
        sb.append(", pn=").append(pn);
        sb.append(", name=").append(name);
        sb.append(", pt=").append(pt);
        sb.append(", ct=").append(ct);
        sb.append(", displayOrder=").append(displayOrder);
        sb.append("]");
        return sb.toString();
    }
}