package com.elefirst.system.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PnInfoExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_202_pn_info
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_202_pn_info
     *
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_202_pn_info
     *
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    protected List<Criteria> oredCriteria;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_202_pn_info
     *
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    protected int limitStart = -1;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_202_pn_info
     *
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     *
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public PnInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     *
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     *
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     *
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public void setLimitStart(int limitStart) {
        this.limitStart = limitStart;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd = limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_202_pn_info
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_202_pn_info
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value,
                                    String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property
                        + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1,
                                    Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property
                        + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("area_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("area_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(String value) {
            addCriterion("area_id =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(String value) {
            addCriterion("area_id <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(String value) {
            addCriterion("area_id >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(String value) {
            addCriterion("area_id >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(String value) {
            addCriterion("area_id <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(String value) {
            addCriterion("area_id <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLike(String value) {
            addCriterion("area_id like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotLike(String value) {
            addCriterion("area_id not like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<String> values) {
            addCriterion("area_id in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<String> values) {
            addCriterion("area_id not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(String value1, String value2) {
            addCriterion("area_id between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(String value1, String value2) {
            addCriterion("area_id not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdIsNull() {
            addCriterion("concentrator_id is null");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdIsNotNull() {
            addCriterion("concentrator_id is not null");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdEqualTo(String value) {
            addCriterion("concentrator_id =", value, "concentratorId");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdNotEqualTo(String value) {
            addCriterion("concentrator_id <>", value, "concentratorId");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdGreaterThan(String value) {
            addCriterion("concentrator_id >", value, "concentratorId");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdGreaterThanOrEqualTo(String value) {
            addCriterion("concentrator_id >=", value, "concentratorId");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdLessThan(String value) {
            addCriterion("concentrator_id <", value, "concentratorId");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdLessThanOrEqualTo(String value) {
            addCriterion("concentrator_id <=", value, "concentratorId");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdLike(String value) {
            addCriterion("concentrator_id like", value, "concentratorId");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdNotLike(String value) {
            addCriterion("concentrator_id not like", value, "concentratorId");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdIn(List<String> values) {
            addCriterion("concentrator_id in", values, "concentratorId");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdNotIn(List<String> values) {
            addCriterion("concentrator_id not in", values, "concentratorId");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdBetween(String value1, String value2) {
            addCriterion("concentrator_id between", value1, value2,
                    "concentratorId");
            return (Criteria) this;
        }

        public Criteria andConcentratorIdNotBetween(String value1, String value2) {
            addCriterion("concentrator_id not between", value1, value2,
                    "concentratorId");
            return (Criteria) this;
        }

        public Criteria andPnIsNull() {
            addCriterion("pn is null");
            return (Criteria) this;
        }

        public Criteria andPnIsNotNull() {
            addCriterion("pn is not null");
            return (Criteria) this;
        }

        public Criteria andPnEqualTo(String value) {
            addCriterion("pn =", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnNotEqualTo(String value) {
            addCriterion("pn <>", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnGreaterThan(String value) {
            addCriterion("pn >", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnGreaterThanOrEqualTo(String value) {
            addCriterion("pn >=", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnLessThan(String value) {
            addCriterion("pn <", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnLessThanOrEqualTo(String value) {
            addCriterion("pn <=", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnLike(String value) {
            addCriterion("pn like", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnNotLike(String value) {
            addCriterion("pn not like", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnIn(List<String> values) {
            addCriterion("pn in", values, "pn");
            return (Criteria) this;
        }

        public Criteria andPnNotIn(List<String> values) {
            addCriterion("pn not in", values, "pn");
            return (Criteria) this;
        }

        public Criteria andPnBetween(String value1, String value2) {
            addCriterion("pn between", value1, value2, "pn");
            return (Criteria) this;
        }

        public Criteria andPnNotBetween(String value1, String value2) {
            addCriterion("pn not between", value1, value2, "pn");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPtIsNull() {
            addCriterion("pt is null");
            return (Criteria) this;
        }

        public Criteria andPtIsNotNull() {
            addCriterion("pt is not null");
            return (Criteria) this;
        }

        public Criteria andPtEqualTo(Double value) {
            addCriterion("pt =", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtNotEqualTo(Double value) {
            addCriterion("pt <>", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtGreaterThan(Double value) {
            addCriterion("pt >", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtGreaterThanOrEqualTo(Double value) {
            addCriterion("pt >=", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtLessThan(Double value) {
            addCriterion("pt <", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtLessThanOrEqualTo(Double value) {
            addCriterion("pt <=", value, "pt");
            return (Criteria) this;
        }

        public Criteria andPtIn(List<Double> values) {
            addCriterion("pt in", values, "pt");
            return (Criteria) this;
        }

        public Criteria andPtNotIn(List<Double> values) {
            addCriterion("pt not in", values, "pt");
            return (Criteria) this;
        }

        public Criteria andPtBetween(Double value1, Double value2) {
            addCriterion("pt between", value1, value2, "pt");
            return (Criteria) this;
        }

        public Criteria andPtNotBetween(Double value1, Double value2) {
            addCriterion("pt not between", value1, value2, "pt");
            return (Criteria) this;
        }

        public Criteria andCtIsNull() {
            addCriterion("ct is null");
            return (Criteria) this;
        }

        public Criteria andCtIsNotNull() {
            addCriterion("ct is not null");
            return (Criteria) this;
        }

        public Criteria andCtEqualTo(Double value) {
            addCriterion("ct =", value, "ct");
            return (Criteria) this;
        }

        public Criteria andCtNotEqualTo(Double value) {
            addCriterion("ct <>", value, "ct");
            return (Criteria) this;
        }

        public Criteria andCtGreaterThan(Double value) {
            addCriterion("ct >", value, "ct");
            return (Criteria) this;
        }

        public Criteria andCtGreaterThanOrEqualTo(Double value) {
            addCriterion("ct >=", value, "ct");
            return (Criteria) this;
        }

        public Criteria andCtLessThan(Double value) {
            addCriterion("ct <", value, "ct");
            return (Criteria) this;
        }

        public Criteria andCtLessThanOrEqualTo(Double value) {
            addCriterion("ct <=", value, "ct");
            return (Criteria) this;
        }

        public Criteria andCtIn(List<Double> values) {
            addCriterion("ct in", values, "ct");
            return (Criteria) this;
        }

        public Criteria andCtNotIn(List<Double> values) {
            addCriterion("ct not in", values, "ct");
            return (Criteria) this;
        }

        public Criteria andCtBetween(Double value1, Double value2) {
            addCriterion("ct between", value1, value2, "ct");
            return (Criteria) this;
        }

        public Criteria andCtNotBetween(Double value1, Double value2) {
            addCriterion("ct not between", value1, value2, "ct");
            return (Criteria) this;
        }

        public Criteria andVoltageStandardIsNull() {
            addCriterion("voltage_standard is null");
            return (Criteria) this;
        }

        public Criteria andVoltageStandardIsNotNull() {
            addCriterion("voltage_standard is not null");
            return (Criteria) this;
        }

        public Criteria andVoltageStandardEqualTo(Double value) {
            addCriterion("voltage_standard =", value, "voltageStandard");
            return (Criteria) this;
        }

        public Criteria andVoltageStandardNotEqualTo(Double value) {
            addCriterion("voltage_standard <>", value, "voltageStandard");
            return (Criteria) this;
        }

        public Criteria andVoltageStandardGreaterThan(Double value) {
            addCriterion("voltage_standard >", value, "voltageStandard");
            return (Criteria) this;
        }

        public Criteria andVoltageStandardGreaterThanOrEqualTo(Double value) {
            addCriterion("voltage_standard >=", value, "voltageStandard");
            return (Criteria) this;
        }

        public Criteria andVoltageStandardLessThan(Double value) {
            addCriterion("voltage_standard <", value, "voltageStandard");
            return (Criteria) this;
        }

        public Criteria andVoltageStandardLessThanOrEqualTo(Double value) {
            addCriterion("voltage_standard <=", value, "voltageStandard");
            return (Criteria) this;
        }

        public Criteria andVoltageStandardIn(List<Double> values) {
            addCriterion("voltage_standard in", values, "voltageStandard");
            return (Criteria) this;
        }

        public Criteria andVoltageStandardNotIn(List<Double> values) {
            addCriterion("voltage_standard not in", values, "voltageStandard");
            return (Criteria) this;
        }

        public Criteria andVoltageStandardBetween(Double value1, Double value2) {
            addCriterion("voltage_standard between", value1, value2,
                    "voltageStandard");
            return (Criteria) this;
        }

        public Criteria andVoltageStandardNotBetween(Double value1,
                                                     Double value2) {
            addCriterion("voltage_standard not between", value1, value2,
                    "voltageStandard");
            return (Criteria) this;
        }

        public Criteria andVoltageUpperLimitIsNull() {
            addCriterion("voltage_upper_limit is null");
            return (Criteria) this;
        }

        public Criteria andVoltageUpperLimitIsNotNull() {
            addCriterion("voltage_upper_limit is not null");
            return (Criteria) this;
        }

        public Criteria andVoltageUpperLimitEqualTo(Double value) {
            addCriterion("voltage_upper_limit =", value, "voltageUpperLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageUpperLimitNotEqualTo(Double value) {
            addCriterion("voltage_upper_limit <>", value, "voltageUpperLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageUpperLimitGreaterThan(Double value) {
            addCriterion("voltage_upper_limit >", value, "voltageUpperLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageUpperLimitGreaterThanOrEqualTo(Double value) {
            addCriterion("voltage_upper_limit >=", value, "voltageUpperLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageUpperLimitLessThan(Double value) {
            addCriterion("voltage_upper_limit <", value, "voltageUpperLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageUpperLimitLessThanOrEqualTo(Double value) {
            addCriterion("voltage_upper_limit <=", value, "voltageUpperLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageUpperLimitIn(List<Double> values) {
            addCriterion("voltage_upper_limit in", values, "voltageUpperLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageUpperLimitNotIn(List<Double> values) {
            addCriterion("voltage_upper_limit not in", values,
                    "voltageUpperLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageUpperLimitBetween(Double value1, Double value2) {
            addCriterion("voltage_upper_limit between", value1, value2,
                    "voltageUpperLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageUpperLimitNotBetween(Double value1,
                                                       Double value2) {
            addCriterion("voltage_upper_limit not between", value1, value2,
                    "voltageUpperLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageLowerLimitIsNull() {
            addCriterion("voltage_lower_limit is null");
            return (Criteria) this;
        }

        public Criteria andVoltageLowerLimitIsNotNull() {
            addCriterion("voltage_lower_limit is not null");
            return (Criteria) this;
        }

        public Criteria andVoltageLowerLimitEqualTo(Double value) {
            addCriterion("voltage_lower_limit =", value, "voltageLowerLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageLowerLimitNotEqualTo(Double value) {
            addCriterion("voltage_lower_limit <>", value, "voltageLowerLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageLowerLimitGreaterThan(Double value) {
            addCriterion("voltage_lower_limit >", value, "voltageLowerLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageLowerLimitGreaterThanOrEqualTo(Double value) {
            addCriterion("voltage_lower_limit >=", value, "voltageLowerLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageLowerLimitLessThan(Double value) {
            addCriterion("voltage_lower_limit <", value, "voltageLowerLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageLowerLimitLessThanOrEqualTo(Double value) {
            addCriterion("voltage_lower_limit <=", value, "voltageLowerLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageLowerLimitIn(List<Double> values) {
            addCriterion("voltage_lower_limit in", values, "voltageLowerLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageLowerLimitNotIn(List<Double> values) {
            addCriterion("voltage_lower_limit not in", values,
                    "voltageLowerLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageLowerLimitBetween(Double value1, Double value2) {
            addCriterion("voltage_lower_limit between", value1, value2,
                    "voltageLowerLimit");
            return (Criteria) this;
        }

        public Criteria andVoltageLowerLimitNotBetween(Double value1,
                                                       Double value2) {
            addCriterion("voltage_lower_limit not between", value1, value2,
                    "voltageLowerLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentStandardIsNull() {
            addCriterion("current_standard is null");
            return (Criteria) this;
        }

        public Criteria andCurrentStandardIsNotNull() {
            addCriterion("current_standard is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentStandardEqualTo(Double value) {
            addCriterion("current_standard =", value, "currentStandard");
            return (Criteria) this;
        }

        public Criteria andCurrentStandardNotEqualTo(Double value) {
            addCriterion("current_standard <>", value, "currentStandard");
            return (Criteria) this;
        }

        public Criteria andCurrentStandardGreaterThan(Double value) {
            addCriterion("current_standard >", value, "currentStandard");
            return (Criteria) this;
        }

        public Criteria andCurrentStandardGreaterThanOrEqualTo(Double value) {
            addCriterion("current_standard >=", value, "currentStandard");
            return (Criteria) this;
        }

        public Criteria andCurrentStandardLessThan(Double value) {
            addCriterion("current_standard <", value, "currentStandard");
            return (Criteria) this;
        }

        public Criteria andCurrentStandardLessThanOrEqualTo(Double value) {
            addCriterion("current_standard <=", value, "currentStandard");
            return (Criteria) this;
        }

        public Criteria andCurrentStandardIn(List<Double> values) {
            addCriterion("current_standard in", values, "currentStandard");
            return (Criteria) this;
        }

        public Criteria andCurrentStandardNotIn(List<Double> values) {
            addCriterion("current_standard not in", values, "currentStandard");
            return (Criteria) this;
        }

        public Criteria andCurrentStandardBetween(Double value1, Double value2) {
            addCriterion("current_standard between", value1, value2,
                    "currentStandard");
            return (Criteria) this;
        }

        public Criteria andCurrentStandardNotBetween(Double value1,
                                                     Double value2) {
            addCriterion("current_standard not between", value1, value2,
                    "currentStandard");
            return (Criteria) this;
        }

        public Criteria andCurrentUpperLimitIsNull() {
            addCriterion("current_upper_limit is null");
            return (Criteria) this;
        }

        public Criteria andCurrentUpperLimitIsNotNull() {
            addCriterion("current_upper_limit is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentUpperLimitEqualTo(Double value) {
            addCriterion("current_upper_limit =", value, "currentUpperLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentUpperLimitNotEqualTo(Double value) {
            addCriterion("current_upper_limit <>", value, "currentUpperLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentUpperLimitGreaterThan(Double value) {
            addCriterion("current_upper_limit >", value, "currentUpperLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentUpperLimitGreaterThanOrEqualTo(Double value) {
            addCriterion("current_upper_limit >=", value, "currentUpperLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentUpperLimitLessThan(Double value) {
            addCriterion("current_upper_limit <", value, "currentUpperLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentUpperLimitLessThanOrEqualTo(Double value) {
            addCriterion("current_upper_limit <=", value, "currentUpperLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentUpperLimitIn(List<Double> values) {
            addCriterion("current_upper_limit in", values, "currentUpperLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentUpperLimitNotIn(List<Double> values) {
            addCriterion("current_upper_limit not in", values,
                    "currentUpperLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentUpperLimitBetween(Double value1, Double value2) {
            addCriterion("current_upper_limit between", value1, value2,
                    "currentUpperLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentUpperLimitNotBetween(Double value1,
                                                       Double value2) {
            addCriterion("current_upper_limit not between", value1, value2,
                    "currentUpperLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentLowerLimitIsNull() {
            addCriterion("current_lower_limit is null");
            return (Criteria) this;
        }

        public Criteria andCurrentLowerLimitIsNotNull() {
            addCriterion("current_lower_limit is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentLowerLimitEqualTo(Double value) {
            addCriterion("current_lower_limit =", value, "currentLowerLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentLowerLimitNotEqualTo(Double value) {
            addCriterion("current_lower_limit <>", value, "currentLowerLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentLowerLimitGreaterThan(Double value) {
            addCriterion("current_lower_limit >", value, "currentLowerLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentLowerLimitGreaterThanOrEqualTo(Double value) {
            addCriterion("current_lower_limit >=", value, "currentLowerLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentLowerLimitLessThan(Double value) {
            addCriterion("current_lower_limit <", value, "currentLowerLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentLowerLimitLessThanOrEqualTo(Double value) {
            addCriterion("current_lower_limit <=", value, "currentLowerLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentLowerLimitIn(List<Double> values) {
            addCriterion("current_lower_limit in", values, "currentLowerLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentLowerLimitNotIn(List<Double> values) {
            addCriterion("current_lower_limit not in", values,
                    "currentLowerLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentLowerLimitBetween(Double value1, Double value2) {
            addCriterion("current_lower_limit between", value1, value2,
                    "currentLowerLimit");
            return (Criteria) this;
        }

        public Criteria andCurrentLowerLimitNotBetween(Double value1,
                                                       Double value2) {
            addCriterion("current_lower_limit not between", value1, value2,
                    "currentLowerLimit");
            return (Criteria) this;
        }

        public Criteria andLoadStandardIsNull() {
            addCriterion("load_standard is null");
            return (Criteria) this;
        }

        public Criteria andLoadStandardIsNotNull() {
            addCriterion("load_standard is not null");
            return (Criteria) this;
        }

        public Criteria andLoadStandardEqualTo(Double value) {
            addCriterion("load_standard =", value, "loadStandard");
            return (Criteria) this;
        }

        public Criteria andLoadStandardNotEqualTo(Double value) {
            addCriterion("load_standard <>", value, "loadStandard");
            return (Criteria) this;
        }

        public Criteria andLoadStandardGreaterThan(Double value) {
            addCriterion("load_standard >", value, "loadStandard");
            return (Criteria) this;
        }

        public Criteria andLoadStandardGreaterThanOrEqualTo(Double value) {
            addCriterion("load_standard >=", value, "loadStandard");
            return (Criteria) this;
        }

        public Criteria andLoadStandardLessThan(Double value) {
            addCriterion("load_standard <", value, "loadStandard");
            return (Criteria) this;
        }

        public Criteria andLoadStandardLessThanOrEqualTo(Double value) {
            addCriterion("load_standard <=", value, "loadStandard");
            return (Criteria) this;
        }

        public Criteria andLoadStandardIn(List<Double> values) {
            addCriterion("load_standard in", values, "loadStandard");
            return (Criteria) this;
        }

        public Criteria andLoadStandardNotIn(List<Double> values) {
            addCriterion("load_standard not in", values, "loadStandard");
            return (Criteria) this;
        }

        public Criteria andLoadStandardBetween(Double value1, Double value2) {
            addCriterion("load_standard between", value1, value2,
                    "loadStandard");
            return (Criteria) this;
        }

        public Criteria andLoadStandardNotBetween(Double value1, Double value2) {
            addCriterion("load_standard not between", value1, value2,
                    "loadStandard");
            return (Criteria) this;
        }

        public Criteria andLoadUpperLimitIsNull() {
            addCriterion("load_upper_limit is null");
            return (Criteria) this;
        }

        public Criteria andLoadUpperLimitIsNotNull() {
            addCriterion("load_upper_limit is not null");
            return (Criteria) this;
        }

        public Criteria andLoadUpperLimitEqualTo(Double value) {
            addCriterion("load_upper_limit =", value, "loadUpperLimit");
            return (Criteria) this;
        }

        public Criteria andLoadUpperLimitNotEqualTo(Double value) {
            addCriterion("load_upper_limit <>", value, "loadUpperLimit");
            return (Criteria) this;
        }

        public Criteria andLoadUpperLimitGreaterThan(Double value) {
            addCriterion("load_upper_limit >", value, "loadUpperLimit");
            return (Criteria) this;
        }

        public Criteria andLoadUpperLimitGreaterThanOrEqualTo(Double value) {
            addCriterion("load_upper_limit >=", value, "loadUpperLimit");
            return (Criteria) this;
        }

        public Criteria andLoadUpperLimitLessThan(Double value) {
            addCriterion("load_upper_limit <", value, "loadUpperLimit");
            return (Criteria) this;
        }

        public Criteria andLoadUpperLimitLessThanOrEqualTo(Double value) {
            addCriterion("load_upper_limit <=", value, "loadUpperLimit");
            return (Criteria) this;
        }

        public Criteria andLoadUpperLimitIn(List<Double> values) {
            addCriterion("load_upper_limit in", values, "loadUpperLimit");
            return (Criteria) this;
        }

        public Criteria andLoadUpperLimitNotIn(List<Double> values) {
            addCriterion("load_upper_limit not in", values, "loadUpperLimit");
            return (Criteria) this;
        }

        public Criteria andLoadUpperLimitBetween(Double value1, Double value2) {
            addCriterion("load_upper_limit between", value1, value2,
                    "loadUpperLimit");
            return (Criteria) this;
        }

        public Criteria andLoadUpperLimitNotBetween(Double value1, Double value2) {
            addCriterion("load_upper_limit not between", value1, value2,
                    "loadUpperLimit");
            return (Criteria) this;
        }

        public Criteria andLoadLowerLimitIsNull() {
            addCriterion("load_lower_limit is null");
            return (Criteria) this;
        }

        public Criteria andLoadLowerLimitIsNotNull() {
            addCriterion("load_lower_limit is not null");
            return (Criteria) this;
        }

        public Criteria andLoadLowerLimitEqualTo(Double value) {
            addCriterion("load_lower_limit =", value, "loadLowerLimit");
            return (Criteria) this;
        }

        public Criteria andLoadLowerLimitNotEqualTo(Double value) {
            addCriterion("load_lower_limit <>", value, "loadLowerLimit");
            return (Criteria) this;
        }

        public Criteria andLoadLowerLimitGreaterThan(Double value) {
            addCriterion("load_lower_limit >", value, "loadLowerLimit");
            return (Criteria) this;
        }

        public Criteria andLoadLowerLimitGreaterThanOrEqualTo(Double value) {
            addCriterion("load_lower_limit >=", value, "loadLowerLimit");
            return (Criteria) this;
        }

        public Criteria andLoadLowerLimitLessThan(Double value) {
            addCriterion("load_lower_limit <", value, "loadLowerLimit");
            return (Criteria) this;
        }

        public Criteria andLoadLowerLimitLessThanOrEqualTo(Double value) {
            addCriterion("load_lower_limit <=", value, "loadLowerLimit");
            return (Criteria) this;
        }

        public Criteria andLoadLowerLimitIn(List<Double> values) {
            addCriterion("load_lower_limit in", values, "loadLowerLimit");
            return (Criteria) this;
        }

        public Criteria andLoadLowerLimitNotIn(List<Double> values) {
            addCriterion("load_lower_limit not in", values, "loadLowerLimit");
            return (Criteria) this;
        }

        public Criteria andLoadLowerLimitBetween(Double value1, Double value2) {
            addCriterion("load_lower_limit between", value1, value2,
                    "loadLowerLimit");
            return (Criteria) this;
        }

        public Criteria andLoadLowerLimitNotBetween(Double value1, Double value2) {
            addCriterion("load_lower_limit not between", value1, value2,
                    "loadLowerLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityStandardIsNull() {
            addCriterion("electricity_standard is null");
            return (Criteria) this;
        }

        public Criteria andElectricityStandardIsNotNull() {
            addCriterion("electricity_standard is not null");
            return (Criteria) this;
        }

        public Criteria andElectricityStandardEqualTo(Double value) {
            addCriterion("electricity_standard =", value, "electricityStandard");
            return (Criteria) this;
        }

        public Criteria andElectricityStandardNotEqualTo(Double value) {
            addCriterion("electricity_standard <>", value,
                    "electricityStandard");
            return (Criteria) this;
        }

        public Criteria andElectricityStandardGreaterThan(Double value) {
            addCriterion("electricity_standard >", value, "electricityStandard");
            return (Criteria) this;
        }

        public Criteria andElectricityStandardGreaterThanOrEqualTo(Double value) {
            addCriterion("electricity_standard >=", value,
                    "electricityStandard");
            return (Criteria) this;
        }

        public Criteria andElectricityStandardLessThan(Double value) {
            addCriterion("electricity_standard <", value, "electricityStandard");
            return (Criteria) this;
        }

        public Criteria andElectricityStandardLessThanOrEqualTo(Double value) {
            addCriterion("electricity_standard <=", value,
                    "electricityStandard");
            return (Criteria) this;
        }

        public Criteria andElectricityStandardIn(List<Double> values) {
            addCriterion("electricity_standard in", values,
                    "electricityStandard");
            return (Criteria) this;
        }

        public Criteria andElectricityStandardNotIn(List<Double> values) {
            addCriterion("electricity_standard not in", values,
                    "electricityStandard");
            return (Criteria) this;
        }

        public Criteria andElectricityStandardBetween(Double value1,
                                                      Double value2) {
            addCriterion("electricity_standard between", value1, value2,
                    "electricityStandard");
            return (Criteria) this;
        }

        public Criteria andElectricityStandardNotBetween(Double value1,
                                                         Double value2) {
            addCriterion("electricity_standard not between", value1, value2,
                    "electricityStandard");
            return (Criteria) this;
        }

        public Criteria andElectricityUpperLimitIsNull() {
            addCriterion("electricity_upper_limit is null");
            return (Criteria) this;
        }

        public Criteria andElectricityUpperLimitIsNotNull() {
            addCriterion("electricity_upper_limit is not null");
            return (Criteria) this;
        }

        public Criteria andElectricityUpperLimitEqualTo(Double value) {
            addCriterion("electricity_upper_limit =", value,
                    "electricityUpperLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityUpperLimitNotEqualTo(Double value) {
            addCriterion("electricity_upper_limit <>", value,
                    "electricityUpperLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityUpperLimitGreaterThan(Double value) {
            addCriterion("electricity_upper_limit >", value,
                    "electricityUpperLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityUpperLimitGreaterThanOrEqualTo(
                Double value) {
            addCriterion("electricity_upper_limit >=", value,
                    "electricityUpperLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityUpperLimitLessThan(Double value) {
            addCriterion("electricity_upper_limit <", value,
                    "electricityUpperLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityUpperLimitLessThanOrEqualTo(Double value) {
            addCriterion("electricity_upper_limit <=", value,
                    "electricityUpperLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityUpperLimitIn(List<Double> values) {
            addCriterion("electricity_upper_limit in", values,
                    "electricityUpperLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityUpperLimitNotIn(List<Double> values) {
            addCriterion("electricity_upper_limit not in", values,
                    "electricityUpperLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityUpperLimitBetween(Double value1,
                                                        Double value2) {
            addCriterion("electricity_upper_limit between", value1, value2,
                    "electricityUpperLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityUpperLimitNotBetween(Double value1,
                                                           Double value2) {
            addCriterion("electricity_upper_limit not between", value1, value2,
                    "electricityUpperLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityLowerLimitIsNull() {
            addCriterion("electricity_lower_limit is null");
            return (Criteria) this;
        }

        public Criteria andElectricityLowerLimitIsNotNull() {
            addCriterion("electricity_lower_limit is not null");
            return (Criteria) this;
        }

        public Criteria andElectricityLowerLimitEqualTo(Double value) {
            addCriterion("electricity_lower_limit =", value,
                    "electricityLowerLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityLowerLimitNotEqualTo(Double value) {
            addCriterion("electricity_lower_limit <>", value,
                    "electricityLowerLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityLowerLimitGreaterThan(Double value) {
            addCriterion("electricity_lower_limit >", value,
                    "electricityLowerLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityLowerLimitGreaterThanOrEqualTo(
                Double value) {
            addCriterion("electricity_lower_limit >=", value,
                    "electricityLowerLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityLowerLimitLessThan(Double value) {
            addCriterion("electricity_lower_limit <", value,
                    "electricityLowerLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityLowerLimitLessThanOrEqualTo(Double value) {
            addCriterion("electricity_lower_limit <=", value,
                    "electricityLowerLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityLowerLimitIn(List<Double> values) {
            addCriterion("electricity_lower_limit in", values,
                    "electricityLowerLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityLowerLimitNotIn(List<Double> values) {
            addCriterion("electricity_lower_limit not in", values,
                    "electricityLowerLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityLowerLimitBetween(Double value1,
                                                        Double value2) {
            addCriterion("electricity_lower_limit between", value1, value2,
                    "electricityLowerLimit");
            return (Criteria) this;
        }

        public Criteria andElectricityLowerLimitNotBetween(Double value1,
                                                           Double value2) {
            addCriterion("electricity_lower_limit not between", value1, value2,
                    "electricityLowerLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorStandardIsNull() {
            addCriterion("power_factor_standard is null");
            return (Criteria) this;
        }

        public Criteria andPowerFactorStandardIsNotNull() {
            addCriterion("power_factor_standard is not null");
            return (Criteria) this;
        }

        public Criteria andPowerFactorStandardEqualTo(Double value) {
            addCriterion("power_factor_standard =", value,
                    "powerFactorStandard");
            return (Criteria) this;
        }

        public Criteria andPowerFactorStandardNotEqualTo(Double value) {
            addCriterion("power_factor_standard <>", value,
                    "powerFactorStandard");
            return (Criteria) this;
        }

        public Criteria andPowerFactorStandardGreaterThan(Double value) {
            addCriterion("power_factor_standard >", value,
                    "powerFactorStandard");
            return (Criteria) this;
        }

        public Criteria andPowerFactorStandardGreaterThanOrEqualTo(Double value) {
            addCriterion("power_factor_standard >=", value,
                    "powerFactorStandard");
            return (Criteria) this;
        }

        public Criteria andPowerFactorStandardLessThan(Double value) {
            addCriterion("power_factor_standard <", value,
                    "powerFactorStandard");
            return (Criteria) this;
        }

        public Criteria andPowerFactorStandardLessThanOrEqualTo(Double value) {
            addCriterion("power_factor_standard <=", value,
                    "powerFactorStandard");
            return (Criteria) this;
        }

        public Criteria andPowerFactorStandardIn(List<Double> values) {
            addCriterion("power_factor_standard in", values,
                    "powerFactorStandard");
            return (Criteria) this;
        }

        public Criteria andPowerFactorStandardNotIn(List<Double> values) {
            addCriterion("power_factor_standard not in", values,
                    "powerFactorStandard");
            return (Criteria) this;
        }

        public Criteria andPowerFactorStandardBetween(Double value1,
                                                      Double value2) {
            addCriterion("power_factor_standard between", value1, value2,
                    "powerFactorStandard");
            return (Criteria) this;
        }

        public Criteria andPowerFactorStandardNotBetween(Double value1,
                                                         Double value2) {
            addCriterion("power_factor_standard not between", value1, value2,
                    "powerFactorStandard");
            return (Criteria) this;
        }

        public Criteria andPowerFactorUpperLimitIsNull() {
            addCriterion("power_factor_upper_limit is null");
            return (Criteria) this;
        }

        public Criteria andPowerFactorUpperLimitIsNotNull() {
            addCriterion("power_factor_upper_limit is not null");
            return (Criteria) this;
        }

        public Criteria andPowerFactorUpperLimitEqualTo(Double value) {
            addCriterion("power_factor_upper_limit =", value,
                    "powerFactorUpperLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorUpperLimitNotEqualTo(Double value) {
            addCriterion("power_factor_upper_limit <>", value,
                    "powerFactorUpperLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorUpperLimitGreaterThan(Double value) {
            addCriterion("power_factor_upper_limit >", value,
                    "powerFactorUpperLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorUpperLimitGreaterThanOrEqualTo(
                Double value) {
            addCriterion("power_factor_upper_limit >=", value,
                    "powerFactorUpperLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorUpperLimitLessThan(Double value) {
            addCriterion("power_factor_upper_limit <", value,
                    "powerFactorUpperLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorUpperLimitLessThanOrEqualTo(Double value) {
            addCriterion("power_factor_upper_limit <=", value,
                    "powerFactorUpperLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorUpperLimitIn(List<Double> values) {
            addCriterion("power_factor_upper_limit in", values,
                    "powerFactorUpperLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorUpperLimitNotIn(List<Double> values) {
            addCriterion("power_factor_upper_limit not in", values,
                    "powerFactorUpperLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorUpperLimitBetween(Double value1,
                                                        Double value2) {
            addCriterion("power_factor_upper_limit between", value1, value2,
                    "powerFactorUpperLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorUpperLimitNotBetween(Double value1,
                                                           Double value2) {
            addCriterion("power_factor_upper_limit not between", value1,
                    value2, "powerFactorUpperLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorLowerLimitIsNull() {
            addCriterion("power_factor_lower_limit is null");
            return (Criteria) this;
        }

        public Criteria andPowerFactorLowerLimitIsNotNull() {
            addCriterion("power_factor_lower_limit is not null");
            return (Criteria) this;
        }

        public Criteria andPowerFactorLowerLimitEqualTo(Double value) {
            addCriterion("power_factor_lower_limit =", value,
                    "powerFactorLowerLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorLowerLimitNotEqualTo(Double value) {
            addCriterion("power_factor_lower_limit <>", value,
                    "powerFactorLowerLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorLowerLimitGreaterThan(Double value) {
            addCriterion("power_factor_lower_limit >", value,
                    "powerFactorLowerLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorLowerLimitGreaterThanOrEqualTo(
                Double value) {
            addCriterion("power_factor_lower_limit >=", value,
                    "powerFactorLowerLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorLowerLimitLessThan(Double value) {
            addCriterion("power_factor_lower_limit <", value,
                    "powerFactorLowerLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorLowerLimitLessThanOrEqualTo(Double value) {
            addCriterion("power_factor_lower_limit <=", value,
                    "powerFactorLowerLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorLowerLimitIn(List<Double> values) {
            addCriterion("power_factor_lower_limit in", values,
                    "powerFactorLowerLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorLowerLimitNotIn(List<Double> values) {
            addCriterion("power_factor_lower_limit not in", values,
                    "powerFactorLowerLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorLowerLimitBetween(Double value1,
                                                        Double value2) {
            addCriterion("power_factor_lower_limit between", value1, value2,
                    "powerFactorLowerLimit");
            return (Criteria) this;
        }

        public Criteria andPowerFactorLowerLimitNotBetween(Double value1,
                                                           Double value2) {
            addCriterion("power_factor_lower_limit not between", value1,
                    value2, "powerFactorLowerLimit");
            return (Criteria) this;
        }

        public Criteria andCreatePersonIsNull() {
            addCriterion("create_person is null");
            return (Criteria) this;
        }

        public Criteria andCreatePersonIsNotNull() {
            addCriterion("create_person is not null");
            return (Criteria) this;
        }

        public Criteria andCreatePersonEqualTo(String value) {
            addCriterion("create_person =", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonNotEqualTo(String value) {
            addCriterion("create_person <>", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonGreaterThan(String value) {
            addCriterion("create_person >", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonGreaterThanOrEqualTo(String value) {
            addCriterion("create_person >=", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonLessThan(String value) {
            addCriterion("create_person <", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonLessThanOrEqualTo(String value) {
            addCriterion("create_person <=", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonLike(String value) {
            addCriterion("create_person like", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonNotLike(String value) {
            addCriterion("create_person not like", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonIn(List<String> values) {
            addCriterion("create_person in", values, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonNotIn(List<String> values) {
            addCriterion("create_person not in", values, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonBetween(String value1, String value2) {
            addCriterion("create_person between", value1, value2,
                    "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonNotBetween(String value1, String value2) {
            addCriterion("create_person not between", value1, value2,
                    "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2,
                    "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonIsNull() {
            addCriterion("update_person is null");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonIsNotNull() {
            addCriterion("update_person is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonEqualTo(String value) {
            addCriterion("update_person =", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonNotEqualTo(String value) {
            addCriterion("update_person <>", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonGreaterThan(String value) {
            addCriterion("update_person >", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonGreaterThanOrEqualTo(String value) {
            addCriterion("update_person >=", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonLessThan(String value) {
            addCriterion("update_person <", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonLessThanOrEqualTo(String value) {
            addCriterion("update_person <=", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonLike(String value) {
            addCriterion("update_person like", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonNotLike(String value) {
            addCriterion("update_person not like", value, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonIn(List<String> values) {
            addCriterion("update_person in", values, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonNotIn(List<String> values) {
            addCriterion("update_person not in", values, "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonBetween(String value1, String value2) {
            addCriterion("update_person between", value1, value2,
                    "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdatePersonNotBetween(String value1, String value2) {
            addCriterion("update_person not between", value1, value2,
                    "updatePerson");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2,
                    "updateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_202_pn_info
     *
     * @mbggenerated Sun Feb 12 18:52:09 CST 2017
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue,
                            String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_202_pn_info
     *
     * @mbggenerated do_not_delete_during_merge Tue Jan 31 00:07:07 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}