package com.elefirst.system.po;

import com.elefirst.base.entity.Page;

import java.util.Date;

public class UserInfo extends Page {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.id
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.user_code
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.user_name
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.password
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.role_name
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.phone
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.mobile
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.email
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.organization_name
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private String organizationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.login_count
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private Integer loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.last_login_date
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private Date lastLoginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.create_person
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.create_date
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.update_person
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private String updatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.update_date
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.expire_time
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.enable
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_sys_user.description
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.id
     *
     * @return the value of t_207_sys_user.id
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.id
     *
     * @param id the value for t_207_sys_user.id
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.user_code
     *
     * @return the value of t_207_sys_user.user_code
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.user_code
     *
     * @param userCode the value for t_207_sys_user.user_code
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.user_name
     *
     * @return the value of t_207_sys_user.user_name
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.user_name
     *
     * @param userName the value for t_207_sys_user.user_name
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.password
     *
     * @return the value of t_207_sys_user.password
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.password
     *
     * @param password the value for t_207_sys_user.password
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.role_name
     *
     * @return the value of t_207_sys_user.role_name
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.role_name
     *
     * @param roleName the value for t_207_sys_user.role_name
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.phone
     *
     * @return the value of t_207_sys_user.phone
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.phone
     *
     * @param phone the value for t_207_sys_user.phone
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.mobile
     *
     * @return the value of t_207_sys_user.mobile
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.mobile
     *
     * @param mobile the value for t_207_sys_user.mobile
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.email
     *
     * @return the value of t_207_sys_user.email
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.email
     *
     * @param email the value for t_207_sys_user.email
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.organization_name
     *
     * @return the value of t_207_sys_user.organization_name
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.organization_name
     *
     * @param organizationName the value for t_207_sys_user.organization_name
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName == null ? null : organizationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.login_count
     *
     * @return the value of t_207_sys_user.login_count
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.login_count
     *
     * @param loginCount the value for t_207_sys_user.login_count
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.last_login_date
     *
     * @return the value of t_207_sys_user.last_login_date
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.last_login_date
     *
     * @param lastLoginDate the value for t_207_sys_user.last_login_date
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.create_person
     *
     * @return the value of t_207_sys_user.create_person
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.create_person
     *
     * @param createPerson the value for t_207_sys_user.create_person
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.create_date
     *
     * @return the value of t_207_sys_user.create_date
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.create_date
     *
     * @param createDate the value for t_207_sys_user.create_date
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.update_person
     *
     * @return the value of t_207_sys_user.update_person
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.update_person
     *
     * @param updatePerson the value for t_207_sys_user.update_person
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson == null ? null : updatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.update_date
     *
     * @return the value of t_207_sys_user.update_date
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.update_date
     *
     * @param updateDate the value for t_207_sys_user.update_date
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.expire_time
     *
     * @return the value of t_207_sys_user.expire_time
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.expire_time
     *
     * @param expireTime the value for t_207_sys_user.expire_time
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.enable
     *
     * @return the value of t_207_sys_user.enable
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.enable
     *
     * @param enable the value for t_207_sys_user.enable
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_sys_user.description
     *
     * @return the value of t_207_sys_user.description
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_sys_user.description
     *
     * @param description the value for t_207_sys_user.description
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_207_sys_user
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserInfo other = (UserInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUserCode() == null ? other.getUserCode() == null : this.getUserCode().equals(other.getUserCode()))
                && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
                && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
                && (this.getRoleName() == null ? other.getRoleName() == null : this.getRoleName().equals(other.getRoleName()))
                && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
                && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
                && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
                && (this.getOrganizationName() == null ? other.getOrganizationName() == null : this.getOrganizationName().equals(other.getOrganizationName()))
                && (this.getLoginCount() == null ? other.getLoginCount() == null : this.getLoginCount().equals(other.getLoginCount()))
                && (this.getLastLoginDate() == null ? other.getLastLoginDate() == null : this.getLastLoginDate().equals(other.getLastLoginDate()))
                && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
                && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
                && (this.getUpdatePerson() == null ? other.getUpdatePerson() == null : this.getUpdatePerson().equals(other.getUpdatePerson()))
                && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
                && (this.getExpireTime() == null ? other.getExpireTime() == null : this.getExpireTime().equals(other.getExpireTime()))
                && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
                && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_207_sys_user
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserCode() == null) ? 0 : getUserCode().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getRoleName() == null) ? 0 : getRoleName().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getOrganizationName() == null) ? 0 : getOrganizationName().hashCode());
        result = prime * result + ((getLoginCount() == null) ? 0 : getLoginCount().hashCode());
        result = prime * result + ((getLastLoginDate() == null) ? 0 : getLastLoginDate().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdatePerson() == null) ? 0 : getUpdatePerson().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getExpireTime() == null) ? 0 : getExpireTime().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_207_sys_user
     *
     * @mbg.generated Mon May 22 16:23:09 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userCode=").append(userCode);
        sb.append(", userName=").append(userName);
        sb.append(", password=").append(password);
        sb.append(", roleName=").append(roleName);
        sb.append(", phone=").append(phone);
        sb.append(", mobile=").append(mobile);
        sb.append(", email=").append(email);
        sb.append(", organizationName=").append(organizationName);
        sb.append(", loginCount=").append(loginCount);
        sb.append(", lastLoginDate=").append(lastLoginDate);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", createDate=").append(createDate);
        sb.append(", updatePerson=").append(updatePerson);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", enable=").append(enable);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }
}