package com.elefirst.system.mapper;

import com.elefirst.system.po.AreaInfo;
import com.elefirst.system.po.AreaInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AreaInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_200_area_info
     *
     * @mbggenerated Sun Jan 29 02:08:48 CST 2017
     */
    int countByExample(AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_200_area_info
     *
     * @mbggenerated Sun Jan 29 02:08:48 CST 2017
     */
    int deleteByExample(AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_200_area_info
     *
     * @mbggenerated Sun Jan 29 02:08:48 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_200_area_info
     *
     * @mbggenerated Sun Jan 29 02:08:48 CST 2017
     */
    int insert(AreaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_200_area_info
     *
     * @mbggenerated Sun Jan 29 02:08:48 CST 2017
     */
    int insertSelective(AreaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_200_area_info
     *
     * @mbggenerated Sun Jan 29 02:08:48 CST 2017
     */
    List<AreaInfo> selectByExample(AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_200_area_info
     *
     * @mbggenerated Sun Jan 29 02:08:48 CST 2017
     */
    AreaInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_200_area_info
     *
     * @mbggenerated Sun Jan 29 02:08:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") AreaInfo record, @Param("example") AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_200_area_info
     *
     * @mbggenerated Sun Jan 29 02:08:48 CST 2017
     */
    int updateByExample(@Param("record") AreaInfo record, @Param("example") AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_200_area_info
     *
     * @mbggenerated Sun Jan 29 02:08:48 CST 2017
     */
    int updateByPrimaryKeySelective(AreaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_200_area_info
     *
     * @mbggenerated Sun Jan 29 02:08:48 CST 2017
     */
    int updateByPrimaryKey(AreaInfo record);
}