package com.elefirst.system.mapper;

import com.elefirst.system.po.AreaInfo;
import com.elefirst.system.po.AreaInfoExample;
import com.elefirst.system.po.AreaInfoWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AreaInfoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     *
     * @mbg.generated Thu Feb 09 16:57:56 CST 2017
     */
    long countByExample(AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     *
     * @mbg.generated Thu Feb 09 16:57:56 CST 2017
     */
    int deleteByExample(AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     *
     * @mbg.generated Thu Feb 09 16:57:56 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     * @mbg.generated Thu Feb 09 16:57:56 CST 2017
     */
    int insert(AreaInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     *
     * @mbg.generated Thu Feb 09 16:57:56 CST 2017
     */
    int insertSelective(AreaInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     *
     * @mbg.generated Thu Feb 09 16:57:56 CST 2017
     */
    List<AreaInfoWithBLOBs> selectByExampleWithBLOBs(AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     * @mbg.generated Thu Feb 09 16:57:56 CST 2017
     */
    List<AreaInfo> selectByExample(AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     * @mbg.generated Thu Feb 09 16:57:56 CST 2017
     */
    AreaInfoWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     *
     * @mbg.generated Thu Feb 09 16:57:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") AreaInfoWithBLOBs record, @Param("example") AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     *
     * @mbg.generated Thu Feb 09 16:57:56 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") AreaInfoWithBLOBs record, @Param("example") AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     *
     * @mbg.generated Thu Feb 09 16:57:56 CST 2017
     */
    int updateByExample(@Param("record") AreaInfo record, @Param("example") AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     * @mbg.generated Thu Feb 09 16:57:56 CST 2017
     */
    int updateByPrimaryKeySelective(AreaInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     *
     * @mbg.generated Thu Feb 09 16:57:56 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(AreaInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_200_area_info
     * @mbg.generated  Thu Feb 09 16:57:56 CST 2017
	 */
	int updateByPrimaryKey(AreaInfo record);
}