package com.elefirst.login.po;

import com.elefirst.base.entity.Page;

public class UserInfoKey extends Page {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_user_info.id
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_user_info.user_name
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_user_info.id
     *
     * @return the value of t_207_user_info.id
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_user_info.id
     *
     * @param id the value for t_207_user_info.id
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_user_info.user_name
     *
     * @return the value of t_207_user_info.user_name
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_user_info.user_name
     *
     * @param userName the value for t_207_user_info.user_name
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_207_user_info
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserInfoKey other = (UserInfoKey) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_207_user_info
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_207_user_info
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append("]");
        return sb.toString();
    }
}