package com.elefirst.login.po;

import java.util.Date;

public class UserInfo extends UserInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_user_info.password
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_user_info.name
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_user_info.salt
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_user_info.login_stat
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    private String loginStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_user_info.login_date
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    private Date loginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_user_info.login_ip
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_207_user_info.stat
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    private String stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_user_info.password
     *
     * @return the value of t_207_user_info.password
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_user_info.password
     *
     * @param password the value for t_207_user_info.password
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_user_info.name
     *
     * @return the value of t_207_user_info.name
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_user_info.name
     *
     * @param name the value for t_207_user_info.name
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_user_info.salt
     *
     * @return the value of t_207_user_info.salt
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_user_info.salt
     *
     * @param salt the value for t_207_user_info.salt
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_user_info.login_stat
     *
     * @return the value of t_207_user_info.login_stat
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public String getLoginStat() {
        return loginStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_user_info.login_stat
     *
     * @param loginStat the value for t_207_user_info.login_stat
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public void setLoginStat(String loginStat) {
        this.loginStat = loginStat == null ? null : loginStat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_user_info.login_date
     *
     * @return the value of t_207_user_info.login_date
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public Date getLoginDate() {
        return loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_user_info.login_date
     *
     * @param loginDate the value for t_207_user_info.login_date
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_user_info.login_ip
     *
     * @return the value of t_207_user_info.login_ip
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_user_info.login_ip
     *
     * @param loginIp the value for t_207_user_info.login_ip
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_207_user_info.stat
     *
     * @return the value of t_207_user_info.stat
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_207_user_info.stat
     *
     * @param stat the value for t_207_user_info.stat
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_207_user_info
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserInfo other = (UserInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
                && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getSalt() == null ? other.getSalt() == null : this.getSalt().equals(other.getSalt()))
                && (this.getLoginStat() == null ? other.getLoginStat() == null : this.getLoginStat().equals(other.getLoginStat()))
                && (this.getLoginDate() == null ? other.getLoginDate() == null : this.getLoginDate().equals(other.getLoginDate()))
                && (this.getLoginIp() == null ? other.getLoginIp() == null : this.getLoginIp().equals(other.getLoginIp()))
                && (this.getStat() == null ? other.getStat() == null : this.getStat().equals(other.getStat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_207_user_info
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSalt() == null) ? 0 : getSalt().hashCode());
        result = prime * result + ((getLoginStat() == null) ? 0 : getLoginStat().hashCode());
        result = prime * result + ((getLoginDate() == null) ? 0 : getLoginDate().hashCode());
        result = prime * result + ((getLoginIp() == null) ? 0 : getLoginIp().hashCode());
        result = prime * result + ((getStat() == null) ? 0 : getStat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_207_user_info
     *
     * @mbggenerated Sun Feb 05 23:05:27 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", password=").append(password);
        sb.append(", name=").append(name);
        sb.append(", salt=").append(salt);
        sb.append(", loginStat=").append(loginStat);
        sb.append(", loginDate=").append(loginDate);
        sb.append(", loginIp=").append(loginIp);
        sb.append(", stat=").append(stat);
        sb.append("]");
        return sb.toString();
    }
}