package com.elefirst.report.po;

import com.elefirst.base.entity.Page;

public class ReportEnergyByHour extends Page{

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.id
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.area_id
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String areaId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.concentrator_id
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String concentratorId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.pn
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String pn;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.total
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String total;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_00
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p00;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_01
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p01;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_02
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p02;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_03
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p03;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_04
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p04;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_05
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p05;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_06
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p06;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_07
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p07;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_08
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p08;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_09
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p09;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_10
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p10;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_11
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p11;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_12
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p12;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_13
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p13;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_14
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p14;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_15
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p15;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_16
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p16;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_17
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p17;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_18
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p18;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_19
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p19;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_20
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p20;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_21
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p21;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_22
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p22;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.p_23
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String p23;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.operation_time
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String operationTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_300_report_energy_by_hour.update_time
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.id
     * @return the value of t_300_report_energy_by_hour.id
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.id
     * @param id  the value for t_300_report_energy_by_hour.id
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.area_id
     * @return the value of t_300_report_energy_by_hour.area_id
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.area_id
     * @param areaId  the value for t_300_report_energy_by_hour.area_id
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.concentrator_id
     *
     * @return the value of t_300_report_energy_by_hour.concentrator_id
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getConcentratorId() {
        return concentratorId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.concentrator_id
     * @param concentratorId  the value for t_300_report_energy_by_hour.concentrator_id
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setConcentratorId(String concentratorId) {
        this.concentratorId = concentratorId == null ? null : concentratorId
                .trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.pn
     * @return the value of t_300_report_energy_by_hour.pn
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getPn() {
        return pn;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.pn
     * @param pn  the value for t_300_report_energy_by_hour.pn
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setPn(String pn) {
        this.pn = pn == null ? null : pn.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.total
     * @return the value of t_300_report_energy_by_hour.total
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.total
     * @param total  the value for t_300_report_energy_by_hour.total
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setTotal(String total) {
        this.total = total == null ? null : total.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_00
     * @return the value of t_300_report_energy_by_hour.p_00
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP00() {
        return p00;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_00
     * @param p00  the value for t_300_report_energy_by_hour.p_00
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP00(String p00) {
        this.p00 = p00 == null ? null : p00.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_01
     * @return the value of t_300_report_energy_by_hour.p_01
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP01() {
        return p01;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_01
     * @param p01  the value for t_300_report_energy_by_hour.p_01
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP01(String p01) {
        this.p01 = p01 == null ? null : p01.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_02
     * @return the value of t_300_report_energy_by_hour.p_02
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP02() {
        return p02;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_02
     * @param p02  the value for t_300_report_energy_by_hour.p_02
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP02(String p02) {
        this.p02 = p02 == null ? null : p02.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_03
     * @return the value of t_300_report_energy_by_hour.p_03
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP03() {
        return p03;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_03
     * @param p03  the value for t_300_report_energy_by_hour.p_03
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP03(String p03) {
        this.p03 = p03 == null ? null : p03.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_04
     * @return the value of t_300_report_energy_by_hour.p_04
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP04() {
        return p04;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_04
     * @param p04  the value for t_300_report_energy_by_hour.p_04
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP04(String p04) {
        this.p04 = p04 == null ? null : p04.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_05
     * @return the value of t_300_report_energy_by_hour.p_05
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP05() {
        return p05;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_05
     * @param p05  the value for t_300_report_energy_by_hour.p_05
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP05(String p05) {
        this.p05 = p05 == null ? null : p05.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_06
     * @return the value of t_300_report_energy_by_hour.p_06
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP06() {
        return p06;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_06
     * @param p06  the value for t_300_report_energy_by_hour.p_06
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP06(String p06) {
        this.p06 = p06 == null ? null : p06.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_07
     * @return the value of t_300_report_energy_by_hour.p_07
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP07() {
        return p07;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_07
     * @param p07  the value for t_300_report_energy_by_hour.p_07
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP07(String p07) {
        this.p07 = p07 == null ? null : p07.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_08
     * @return the value of t_300_report_energy_by_hour.p_08
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP08() {
        return p08;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_08
     * @param p08  the value for t_300_report_energy_by_hour.p_08
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP08(String p08) {
        this.p08 = p08 == null ? null : p08.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_09
     * @return the value of t_300_report_energy_by_hour.p_09
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP09() {
        return p09;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_09
     * @param p09  the value for t_300_report_energy_by_hour.p_09
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP09(String p09) {
        this.p09 = p09 == null ? null : p09.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_10
     * @return the value of t_300_report_energy_by_hour.p_10
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP10() {
        return p10;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_10
     * @param p10  the value for t_300_report_energy_by_hour.p_10
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP10(String p10) {
        this.p10 = p10 == null ? null : p10.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_11
     * @return the value of t_300_report_energy_by_hour.p_11
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP11() {
        return p11;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_11
     * @param p11  the value for t_300_report_energy_by_hour.p_11
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP11(String p11) {
        this.p11 = p11 == null ? null : p11.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_12
     * @return the value of t_300_report_energy_by_hour.p_12
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP12() {
        return p12;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_12
     * @param p12  the value for t_300_report_energy_by_hour.p_12
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP12(String p12) {
        this.p12 = p12 == null ? null : p12.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_13
     * @return the value of t_300_report_energy_by_hour.p_13
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP13() {
        return p13;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_13
     * @param p13  the value for t_300_report_energy_by_hour.p_13
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP13(String p13) {
        this.p13 = p13 == null ? null : p13.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_14
     * @return the value of t_300_report_energy_by_hour.p_14
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP14() {
        return p14;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_14
     * @param p14  the value for t_300_report_energy_by_hour.p_14
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP14(String p14) {
        this.p14 = p14 == null ? null : p14.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_15
     * @return the value of t_300_report_energy_by_hour.p_15
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP15() {
        return p15;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_15
     * @param p15  the value for t_300_report_energy_by_hour.p_15
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP15(String p15) {
        this.p15 = p15 == null ? null : p15.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_16
     * @return the value of t_300_report_energy_by_hour.p_16
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP16() {
        return p16;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_16
     * @param p16  the value for t_300_report_energy_by_hour.p_16
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP16(String p16) {
        this.p16 = p16 == null ? null : p16.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_17
     * @return the value of t_300_report_energy_by_hour.p_17
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP17() {
        return p17;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_17
     * @param p17  the value for t_300_report_energy_by_hour.p_17
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP17(String p17) {
        this.p17 = p17 == null ? null : p17.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_18
     * @return the value of t_300_report_energy_by_hour.p_18
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP18() {
        return p18;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_18
     * @param p18  the value for t_300_report_energy_by_hour.p_18
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP18(String p18) {
        this.p18 = p18 == null ? null : p18.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_19
     * @return the value of t_300_report_energy_by_hour.p_19
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP19() {
        return p19;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_19
     * @param p19  the value for t_300_report_energy_by_hour.p_19
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP19(String p19) {
        this.p19 = p19 == null ? null : p19.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_20
     * @return the value of t_300_report_energy_by_hour.p_20
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP20() {
        return p20;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_20
     * @param p20  the value for t_300_report_energy_by_hour.p_20
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP20(String p20) {
        this.p20 = p20 == null ? null : p20.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_21
     * @return the value of t_300_report_energy_by_hour.p_21
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP21() {
        return p21;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_21
     * @param p21  the value for t_300_report_energy_by_hour.p_21
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP21(String p21) {
        this.p21 = p21 == null ? null : p21.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_22
     * @return the value of t_300_report_energy_by_hour.p_22
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP22() {
        return p22;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_22
     * @param p22  the value for t_300_report_energy_by_hour.p_22
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP22(String p22) {
        this.p22 = p22 == null ? null : p22.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.p_23
     * @return the value of t_300_report_energy_by_hour.p_23
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getP23() {
        return p23;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.p_23
     * @param p23  the value for t_300_report_energy_by_hour.p_23
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setP23(String p23) {
        this.p23 = p23 == null ? null : p23.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.operation_time
     *
     * @return the value of t_300_report_energy_by_hour.operation_time
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.operation_time
     *
     * @param operationTime the value for t_300_report_energy_by_hour.operation_time
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setOperationTime(String operationTime) {
        this.operationTime = operationTime == null ? null : operationTime
                .trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_300_report_energy_by_hour.update_time
     *
     * @return the value of t_300_report_energy_by_hour.update_time
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_300_report_energy_by_hour.update_time
     *
     * @param updateTime the value for t_300_report_energy_by_hour.update_time
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_300_report_energy_by_hour
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ReportEnergyByHour other = (ReportEnergyByHour) that;
        return (this.getId() == null ? other.getId() == null : this.getId()
                .equals(other.getId()))
                && (this.getAreaId() == null ? other.getAreaId() == null : this
                .getAreaId().equals(other.getAreaId()))
                && (this.getConcentratorId() == null ? other
                .getConcentratorId() == null : this.getConcentratorId()
                .equals(other.getConcentratorId()))
                && (this.getPn() == null ? other.getPn() == null : this.getPn()
                .equals(other.getPn()))
                && (this.getTotal() == null ? other.getTotal() == null : this
                .getTotal().equals(other.getTotal()))
                && (this.getP00() == null ? other.getP00() == null : this
                .getP00().equals(other.getP00()))
                && (this.getP01() == null ? other.getP01() == null : this
                .getP01().equals(other.getP01()))
                && (this.getP02() == null ? other.getP02() == null : this
                .getP02().equals(other.getP02()))
                && (this.getP03() == null ? other.getP03() == null : this
                .getP03().equals(other.getP03()))
                && (this.getP04() == null ? other.getP04() == null : this
                .getP04().equals(other.getP04()))
                && (this.getP05() == null ? other.getP05() == null : this
                .getP05().equals(other.getP05()))
                && (this.getP06() == null ? other.getP06() == null : this
                .getP06().equals(other.getP06()))
                && (this.getP07() == null ? other.getP07() == null : this
                .getP07().equals(other.getP07()))
                && (this.getP08() == null ? other.getP08() == null : this
                .getP08().equals(other.getP08()))
                && (this.getP09() == null ? other.getP09() == null : this
                .getP09().equals(other.getP09()))
                && (this.getP10() == null ? other.getP10() == null : this
                .getP10().equals(other.getP10()))
                && (this.getP11() == null ? other.getP11() == null : this
                .getP11().equals(other.getP11()))
                && (this.getP12() == null ? other.getP12() == null : this
                .getP12().equals(other.getP12()))
                && (this.getP13() == null ? other.getP13() == null : this
                .getP13().equals(other.getP13()))
                && (this.getP14() == null ? other.getP14() == null : this
                .getP14().equals(other.getP14()))
                && (this.getP15() == null ? other.getP15() == null : this
                .getP15().equals(other.getP15()))
                && (this.getP16() == null ? other.getP16() == null : this
                .getP16().equals(other.getP16()))
                && (this.getP17() == null ? other.getP17() == null : this
                .getP17().equals(other.getP17()))
                && (this.getP18() == null ? other.getP18() == null : this
                .getP18().equals(other.getP18()))
                && (this.getP19() == null ? other.getP19() == null : this
                .getP19().equals(other.getP19()))
                && (this.getP20() == null ? other.getP20() == null : this
                .getP20().equals(other.getP20()))
                && (this.getP21() == null ? other.getP21() == null : this
                .getP21().equals(other.getP21()))
                && (this.getP22() == null ? other.getP22() == null : this
                .getP22().equals(other.getP22()))
                && (this.getP23() == null ? other.getP23() == null : this
                .getP23().equals(other.getP23()))
                && (this.getOperationTime() == null ? other.getOperationTime() == null
                : this.getOperationTime().equals(
                other.getOperationTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null
                : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_300_report_energy_by_hour
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result
                + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
        result = prime
                * result
                + ((getConcentratorId() == null) ? 0 : getConcentratorId()
                .hashCode());
        result = prime * result + ((getPn() == null) ? 0 : getPn().hashCode());
        result = prime * result
                + ((getTotal() == null) ? 0 : getTotal().hashCode());
        result = prime * result
                + ((getP00() == null) ? 0 : getP00().hashCode());
        result = prime * result
                + ((getP01() == null) ? 0 : getP01().hashCode());
        result = prime * result
                + ((getP02() == null) ? 0 : getP02().hashCode());
        result = prime * result
                + ((getP03() == null) ? 0 : getP03().hashCode());
        result = prime * result
                + ((getP04() == null) ? 0 : getP04().hashCode());
        result = prime * result
                + ((getP05() == null) ? 0 : getP05().hashCode());
        result = prime * result
                + ((getP06() == null) ? 0 : getP06().hashCode());
        result = prime * result
                + ((getP07() == null) ? 0 : getP07().hashCode());
        result = prime * result
                + ((getP08() == null) ? 0 : getP08().hashCode());
        result = prime * result
                + ((getP09() == null) ? 0 : getP09().hashCode());
        result = prime * result
                + ((getP10() == null) ? 0 : getP10().hashCode());
        result = prime * result
                + ((getP11() == null) ? 0 : getP11().hashCode());
        result = prime * result
                + ((getP12() == null) ? 0 : getP12().hashCode());
        result = prime * result
                + ((getP13() == null) ? 0 : getP13().hashCode());
        result = prime * result
                + ((getP14() == null) ? 0 : getP14().hashCode());
        result = prime * result
                + ((getP15() == null) ? 0 : getP15().hashCode());
        result = prime * result
                + ((getP16() == null) ? 0 : getP16().hashCode());
        result = prime * result
                + ((getP17() == null) ? 0 : getP17().hashCode());
        result = prime * result
                + ((getP18() == null) ? 0 : getP18().hashCode());
        result = prime * result
                + ((getP19() == null) ? 0 : getP19().hashCode());
        result = prime * result
                + ((getP20() == null) ? 0 : getP20().hashCode());
        result = prime * result
                + ((getP21() == null) ? 0 : getP21().hashCode());
        result = prime * result
                + ((getP22() == null) ? 0 : getP22().hashCode());
        result = prime * result
                + ((getP23() == null) ? 0 : getP23().hashCode());
        result = prime
                * result
                + ((getOperationTime() == null) ? 0 : getOperationTime()
                .hashCode());
        result = prime * result
                + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_300_report_energy_by_hour
     *
     * @mbggenerated Wed May 03 01:35:00 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", areaId=").append(areaId);
        sb.append(", concentratorId=").append(concentratorId);
        sb.append(", pn=").append(pn);
        sb.append(", total=").append(total);
        sb.append(", p00=").append(p00);
        sb.append(", p01=").append(p01);
        sb.append(", p02=").append(p02);
        sb.append(", p03=").append(p03);
        sb.append(", p04=").append(p04);
        sb.append(", p05=").append(p05);
        sb.append(", p06=").append(p06);
        sb.append(", p07=").append(p07);
        sb.append(", p08=").append(p08);
        sb.append(", p09=").append(p09);
        sb.append(", p10=").append(p10);
        sb.append(", p11=").append(p11);
        sb.append(", p12=").append(p12);
		sb.append(", p13=").append(p13);
		sb.append(", p14=").append(p14);
		sb.append(", p15=").append(p15);
		sb.append(", p16=").append(p16);
		sb.append(", p17=").append(p17);
		sb.append(", p18=").append(p18);
		sb.append(", p19=").append(p19);
		sb.append(", p20=").append(p20);
		sb.append(", p21=").append(p21);
		sb.append(", p22=").append(p22);
		sb.append(", p23=").append(p23);
		sb.append(", operationTime=").append(operationTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append("]");
		return sb.toString();
	}
}