package com.elefirst.graph.mapper;

import com.elefirst.graph.po.GraphTemplate;
import com.elefirst.graph.po.GraphTemplateExample;
import com.elefirst.graph.po.GraphTemplateWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GraphTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    long countByExample(GraphTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    int deleteByExample(GraphTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    int insert(GraphTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    int insertSelective(GraphTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    List<GraphTemplateWithBLOBs> selectByExampleWithBLOBs(GraphTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    List<GraphTemplate> selectByExample(GraphTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    GraphTemplateWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") GraphTemplateWithBLOBs record, @Param("example") GraphTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") GraphTemplateWithBLOBs record, @Param("example") GraphTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    int updateByExample(@Param("record") GraphTemplate record, @Param("example") GraphTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    int updateByPrimaryKeySelective(GraphTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(GraphTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_205_graph_template
     *
     * @mbg.generated Tue May 23 18:40:58 CST 2017
     */
    int updateByPrimaryKey(GraphTemplate record);
}