package com.elefirst.graph.mapper;

import com.elefirst.graph.po.GraphToolbar;
import com.elefirst.graph.po.GraphToolbarExample;
import com.elefirst.graph.po.GraphToolbarWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GraphToolbarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    int countByExample(GraphToolbarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    int deleteByExample(GraphToolbarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    int insert(GraphToolbarWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    int insertSelective(GraphToolbarWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    List<GraphToolbarWithBLOBs> selectByExampleWithBLOBs(GraphToolbarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    List<GraphToolbar> selectByExample(GraphToolbarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    GraphToolbarWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    int updateByExampleSelective(@Param("record") GraphToolbarWithBLOBs record, @Param("example") GraphToolbarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") GraphToolbarWithBLOBs record, @Param("example") GraphToolbarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    int updateByExample(@Param("record") GraphToolbar record, @Param("example") GraphToolbarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    int updateByPrimaryKeySelective(GraphToolbarWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(GraphToolbarWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_204_graph_toolbar
     *
     * @mbggenerated Wed Feb 01 16:18:13 CST 2017
     */
    int updateByPrimaryKey(GraphToolbar record);
}