package com.elefirst.power.po;

import com.elefirst.base.entity.Page;

public class DataF21Rate extends Page {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_035_type_two_data_fn21_rate.id
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_035_type_two_data_fn21_rate.area_id
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_035_type_two_data_fn21_rate.concentrator_id
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    private String concentratorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_035_type_two_data_fn21_rate.pn
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    private String pn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_035_type_two_data_fn21_rate.rate_seq
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    private String rateSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_035_type_two_data_fn21_rate.positiveActivePower
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    private String positiveactivepower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_035_type_two_data_fn21_rate.sendTime
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    private String sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_035_type_two_data_fn21_rate.frozen_month
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    private String frozenMonth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_035_type_two_data_fn21_rate.id
     *
     * @return the value of t_035_type_two_data_fn21_rate.id
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_035_type_two_data_fn21_rate.id
     *
     * @param id the value for t_035_type_two_data_fn21_rate.id
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_035_type_two_data_fn21_rate.area_id
     *
     * @return the value of t_035_type_two_data_fn21_rate.area_id
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_035_type_two_data_fn21_rate.area_id
     *
     * @param areaId the value for t_035_type_two_data_fn21_rate.area_id
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_035_type_two_data_fn21_rate.concentrator_id
     *
     * @return the value of t_035_type_two_data_fn21_rate.concentrator_id
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public String getConcentratorId() {
        return concentratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_035_type_two_data_fn21_rate.concentrator_id
     *
     * @param concentratorId the value for t_035_type_two_data_fn21_rate.concentrator_id
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public void setConcentratorId(String concentratorId) {
        this.concentratorId = concentratorId == null ? null : concentratorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_035_type_two_data_fn21_rate.pn
     *
     * @return the value of t_035_type_two_data_fn21_rate.pn
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public String getPn() {
        return pn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_035_type_two_data_fn21_rate.pn
     *
     * @param pn the value for t_035_type_two_data_fn21_rate.pn
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public void setPn(String pn) {
        this.pn = pn == null ? null : pn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_035_type_two_data_fn21_rate.rate_seq
     *
     * @return the value of t_035_type_two_data_fn21_rate.rate_seq
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public String getRateSeq() {
        return rateSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_035_type_two_data_fn21_rate.rate_seq
     *
     * @param rateSeq the value for t_035_type_two_data_fn21_rate.rate_seq
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public void setRateSeq(String rateSeq) {
        this.rateSeq = rateSeq == null ? null : rateSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_035_type_two_data_fn21_rate.positiveActivePower
     *
     * @return the value of t_035_type_two_data_fn21_rate.positiveActivePower
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public String getPositiveactivepower() {
        return positiveactivepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_035_type_two_data_fn21_rate.positiveActivePower
     *
     * @param positiveactivepower the value for t_035_type_two_data_fn21_rate.positiveActivePower
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public void setPositiveactivepower(String positiveactivepower) {
        this.positiveactivepower = positiveactivepower == null ? null : positiveactivepower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_035_type_two_data_fn21_rate.sendTime
     *
     * @return the value of t_035_type_two_data_fn21_rate.sendTime
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public String getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_035_type_two_data_fn21_rate.sendTime
     *
     * @param sendtime the value for t_035_type_two_data_fn21_rate.sendTime
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public void setSendtime(String sendtime) {
        this.sendtime = sendtime == null ? null : sendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_035_type_two_data_fn21_rate.frozen_month
     *
     * @return the value of t_035_type_two_data_fn21_rate.frozen_month
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public String getFrozenMonth() {
        return frozenMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_035_type_two_data_fn21_rate.frozen_month
     *
     * @param frozenMonth the value for t_035_type_two_data_fn21_rate.frozen_month
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    public void setFrozenMonth(String frozenMonth) {
        this.frozenMonth = frozenMonth == null ? null : frozenMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21_rate
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DataF21Rate other = (DataF21Rate) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getAreaId() == null ? other.getAreaId() == null : this.getAreaId().equals(other.getAreaId()))
                && (this.getConcentratorId() == null ? other.getConcentratorId() == null : this.getConcentratorId().equals(other.getConcentratorId()))
                && (this.getPn() == null ? other.getPn() == null : this.getPn().equals(other.getPn()))
                && (this.getRateSeq() == null ? other.getRateSeq() == null : this.getRateSeq().equals(other.getRateSeq()))
                && (this.getPositiveactivepower() == null ? other.getPositiveactivepower() == null : this.getPositiveactivepower().equals(other.getPositiveactivepower()))
                && (this.getSendtime() == null ? other.getSendtime() == null : this.getSendtime().equals(other.getSendtime()))
                && (this.getFrozenMonth() == null ? other.getFrozenMonth() == null : this.getFrozenMonth().equals(other.getFrozenMonth()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21_rate
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
        result = prime * result + ((getConcentratorId() == null) ? 0 : getConcentratorId().hashCode());
        result = prime * result + ((getPn() == null) ? 0 : getPn().hashCode());
        result = prime * result + ((getRateSeq() == null) ? 0 : getRateSeq().hashCode());
        result = prime * result + ((getPositiveactivepower() == null) ? 0 : getPositiveactivepower().hashCode());
        result = prime * result + ((getSendtime() == null) ? 0 : getSendtime().hashCode());
        result = prime * result + ((getFrozenMonth() == null) ? 0 : getFrozenMonth().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21_rate
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", areaId=").append(areaId);
        sb.append(", concentratorId=").append(concentratorId);
        sb.append(", pn=").append(pn);
        sb.append(", rateSeq=").append(rateSeq);
        sb.append(", positiveactivepower=").append(positiveactivepower);
        sb.append(", sendtime=").append(sendtime);
        sb.append(", frozenMonth=").append(frozenMonth);
        sb.append("]");
        return sb.toString();
    }
}