package com.elefirst.power.mapper;

import com.elefirst.power.po.DataF25FrozenDay;
import com.elefirst.power.po.DataF25FrozenDayExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DataF25FrozenDayCustomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25_frozen_day
     *
     * @mbggenerated Wed Mar 08 22:44:24 CST 2017
     */
    List<DataF25FrozenDay> selectSumByExample(DataF25FrozenDayExample example);
}