package com.elefirst.power.mapper;

import com.elefirst.power.po.DataF21;
import com.elefirst.power.po.DataF21Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DataF21Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21
     *
     * @mbggenerated Mon Apr 24 20:48:17 CST 2017
     */
    int countByExample(DataF21Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21
     *
     * @mbggenerated Mon Apr 24 20:48:17 CST 2017
     */
    int deleteByExample(DataF21Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21
     *
     * @mbggenerated Mon Apr 24 20:48:17 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21
     *
     * @mbggenerated Mon Apr 24 20:48:17 CST 2017
     */
    int insert(DataF21 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21
     *
     * @mbggenerated Mon Apr 24 20:48:17 CST 2017
     */
    int insertSelective(DataF21 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21
     *
     * @mbggenerated Mon Apr 24 20:48:17 CST 2017
     */
    List<DataF21> selectByExample(DataF21Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21
     *
     * @mbggenerated Mon Apr 24 20:48:17 CST 2017
     */
    DataF21 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21
     *
     * @mbggenerated Mon Apr 24 20:48:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") DataF21 record, @Param("example") DataF21Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21
     *
     * @mbggenerated Mon Apr 24 20:48:17 CST 2017
     */
    int updateByExample(@Param("record") DataF21 record, @Param("example") DataF21Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21
     *
     * @mbggenerated Mon Apr 24 20:48:17 CST 2017
     */
    int updateByPrimaryKeySelective(DataF21 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21
     *
     * @mbggenerated Mon Apr 24 20:48:17 CST 2017
     */
    int updateByPrimaryKey(DataF21 record);
}