package com.elefirst.power.mapper;

import com.elefirst.power.po.DataF25FrozenMinute;
import com.elefirst.power.po.DataF25FrozenMinuteExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DataF25FrozenMinuteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_fn25_frozen_per_15m
     *
     * @mbggenerated Sun Apr 09 15:11:54 CST 2017
     */
    int countByExample(DataF25FrozenMinuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_fn25_frozen_per_15m
     *
     * @mbggenerated Sun Apr 09 15:11:54 CST 2017
     */
    int deleteByExample(DataF25FrozenMinuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_fn25_frozen_per_15m
     *
     * @mbggenerated Sun Apr 09 15:11:54 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_fn25_frozen_per_15m
     *
     * @mbggenerated Sun Apr 09 15:11:54 CST 2017
     */
    int insert(DataF25FrozenMinute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_fn25_frozen_per_15m
     *
     * @mbggenerated Sun Apr 09 15:11:54 CST 2017
     */
    int insertSelective(DataF25FrozenMinute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_fn25_frozen_per_15m
     *
     * @mbggenerated Sun Apr 09 15:11:54 CST 2017
     */
    List<DataF25FrozenMinute> selectByExample(DataF25FrozenMinuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_fn25_frozen_per_15m
     *
     * @mbggenerated Sun Apr 09 15:11:54 CST 2017
     */
    DataF25FrozenMinute selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_fn25_frozen_per_15m
     *
     * @mbggenerated Sun Apr 09 15:11:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") DataF25FrozenMinute record, @Param("example") DataF25FrozenMinuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_fn25_frozen_per_15m
     *
     * @mbggenerated Sun Apr 09 15:11:54 CST 2017
     */
    int updateByExample(@Param("record") DataF25FrozenMinute record, @Param("example") DataF25FrozenMinuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_fn25_frozen_per_15m
     *
     * @mbggenerated Sun Apr 09 15:11:54 CST 2017
     */
    int updateByPrimaryKeySelective(DataF25FrozenMinute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_fn25_frozen_per_15m
     *
     * @mbggenerated Sun Apr 09 15:11:54 CST 2017
     */
    int updateByPrimaryKey(DataF25FrozenMinute record);
}