package com.elefirst.power.mapper;

import com.elefirst.power.po.DataF5Rate;
import com.elefirst.power.po.DataF5RateExample;

import java.util.List;

public interface DataF5RateCustomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_030_type_two_data_fn5_rate
     *
     * @mbg.generated Wed Apr 19 11:27:02 CST 2017
     */
    List<DataF5Rate> selectSumByExample(DataF5RateExample example);
}