package com.elefirst.power.mapper;

import com.elefirst.power.po.DataF21Rate;
import com.elefirst.power.po.DataF21RateExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DataF21RateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21_rate
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    long countByExample(DataF21RateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21_rate
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    int deleteByExample(DataF21RateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21_rate
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    int insert(DataF21Rate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21_rate
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    int insertSelective(DataF21Rate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21_rate
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    List<DataF21Rate> selectByExample(DataF21RateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21_rate
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") DataF21Rate record, @Param("example") DataF21RateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21_rate
     *
     * @mbg.generated Wed May 31 16:09:52 CST 2017
     */
    int updateByExample(@Param("record") DataF21Rate record, @Param("example") DataF21RateExample example);
}