package com.elefirst.power.mapper;

import com.elefirst.power.po.DataF21;
import com.elefirst.power.po.DataF21Example;

import java.util.List;

public interface DataF21CustomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_035_type_two_data_fn21
     *
     * @mbggenerated Mon Apr 24 20:48:17 CST 2017
     */
    List<DataF21> selectSumByExample(DataF21Example example);
}