package com.elefirst.power.mapper;

import com.elefirst.power.po.DataF25FrozenDay;
import com.elefirst.power.po.DataF25FrozenDayExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DataF25FrozenDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25_frozen_day
     *
     * @mbggenerated Wed Mar 08 22:44:24 CST 2017
     */
    int countByExample(DataF25FrozenDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25_frozen_day
     *
     * @mbggenerated Wed Mar 08 22:44:24 CST 2017
     */
    int deleteByExample(DataF25FrozenDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25_frozen_day
     *
     * @mbggenerated Wed Mar 08 22:44:24 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25_frozen_day
     *
     * @mbggenerated Wed Mar 08 22:44:24 CST 2017
     */
    int insert(DataF25FrozenDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25_frozen_day
     *
     * @mbggenerated Wed Mar 08 22:44:24 CST 2017
     */
    int insertSelective(DataF25FrozenDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25_frozen_day
     *
     * @mbggenerated Wed Mar 08 22:44:24 CST 2017
     */
    List<DataF25FrozenDay> selectByExample(DataF25FrozenDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25_frozen_day
     *
     * @mbggenerated Wed Mar 08 22:44:24 CST 2017
     */
    DataF25FrozenDay selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25_frozen_day
     *
     * @mbggenerated Wed Mar 08 22:44:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") DataF25FrozenDay record, @Param("example") DataF25FrozenDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25_frozen_day
     *
     * @mbggenerated Wed Mar 08 22:44:24 CST 2017
     */
    int updateByExample(@Param("record") DataF25FrozenDay record, @Param("example") DataF25FrozenDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25_frozen_day
     *
     * @mbggenerated Wed Mar 08 22:44:24 CST 2017
     */
    int updateByPrimaryKeySelective(DataF25FrozenDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25_frozen_day
     *
     * @mbggenerated Wed Mar 08 22:44:24 CST 2017
     */
    int updateByPrimaryKey(DataF25FrozenDay record);
}