package com.elefirst.power.mapper;

import com.elefirst.power.po.DataF25FrozenMinute;
import com.elefirst.power.po.DataF25FrozenMinuteExample;
import com.elefirst.power.po.DataF25FrozenMinuteWithF21;
import com.elefirst.power.po.DataF25FrozenMinuteWithF5;

import java.util.List;

public interface DataF25FrozenMinuteCustomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25_frozen_day
     *
     * @mbggenerated Wed Mar 08 22:44:24 CST 2017
     */
    List<DataF25FrozenMinute> selectSumByExample(DataF25FrozenMinuteExample example);

    List<DataF25FrozenMinuteWithF5> selectSumWithF5ByExample(DataF25FrozenMinuteExample example);

    List<DataF25FrozenMinuteWithF21> selectSumWithF21ByExample(DataF25FrozenMinuteExample example);

    List<DataF25FrozenMinuteWithF5> selectStatisticsWithF5DailyByExample(DataF25FrozenMinuteExample example);

    List<DataF25FrozenMinuteWithF21> selectStatisticsWithF21MonthlyByExample(DataF25FrozenMinuteExample example);

}