package com.elefirst.power.mapper;

import com.elefirst.power.po.DataF105;
import com.elefirst.power.po.DataF105Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DataF105Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_037_type_one_data_fn105
     *
     * @mbg.generated Thu Apr 20 09:41:10 CST 2017
     */
    long countByExample(DataF105Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_037_type_one_data_fn105
     *
     * @mbg.generated Thu Apr 20 09:41:10 CST 2017
     */
    int deleteByExample(DataF105Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_037_type_one_data_fn105
     *
     * @mbg.generated Thu Apr 20 09:41:10 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_037_type_one_data_fn105
     *
     * @mbg.generated Thu Apr 20 09:41:10 CST 2017
     */
    int insert(DataF105 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_037_type_one_data_fn105
     *
     * @mbg.generated Thu Apr 20 09:41:10 CST 2017
     */
    int insertSelective(DataF105 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_037_type_one_data_fn105
     *
     * @mbg.generated Thu Apr 20 09:41:10 CST 2017
     */
    List<DataF105> selectByExample(DataF105Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_037_type_one_data_fn105
     *
     * @mbg.generated Thu Apr 20 09:41:10 CST 2017
     */
    DataF105 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_037_type_one_data_fn105
     *
     * @mbg.generated Thu Apr 20 09:41:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") DataF105 record, @Param("example") DataF105Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_037_type_one_data_fn105
     *
     * @mbg.generated Thu Apr 20 09:41:10 CST 2017
     */
    int updateByExample(@Param("record") DataF105 record, @Param("example") DataF105Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_037_type_one_data_fn105
     *
     * @mbg.generated Thu Apr 20 09:41:10 CST 2017
     */
    int updateByPrimaryKeySelective(DataF105 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_037_type_one_data_fn105
     *
     * @mbg.generated Thu Apr 20 09:41:10 CST 2017
     */
    int updateByPrimaryKey(DataF105 record);
}