package com.elefirst.power.mapper;

import com.elefirst.power.po.DataF25;
import com.elefirst.power.po.DataF25Example;

import java.util.List;

public interface DataF25CustomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_003_type_one_data_fn25
     *
     * @mbggenerated Thu Feb 02 02:46:16 CST 2017
     */
    List<DataF25> selectSumByExample(DataF25Example example);
}