package com.elefirst.power.mapper;

import com.elefirst.power.po.PnStat;
import com.elefirst.power.po.PnStatExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PnStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_020_pn_stat
     *
     * @mbggenerated Mon Feb 06 20:11:27 CST 2017
     */
    int countByExample(PnStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_020_pn_stat
     *
     * @mbggenerated Mon Feb 06 20:11:27 CST 2017
     */
    int deleteByExample(PnStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_020_pn_stat
     *
     * @mbggenerated Mon Feb 06 20:11:27 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_020_pn_stat
     *
     * @mbggenerated Mon Feb 06 20:11:27 CST 2017
     */
    int insert(PnStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_020_pn_stat
     *
     * @mbggenerated Mon Feb 06 20:11:27 CST 2017
     */
    int insertSelective(PnStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_020_pn_stat
     *
     * @mbggenerated Mon Feb 06 20:11:27 CST 2017
     */
    List<PnStat> selectByExample(PnStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_020_pn_stat
     *
     * @mbggenerated Mon Feb 06 20:11:27 CST 2017
     */
    PnStat selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_020_pn_stat
     *
     * @mbggenerated Mon Feb 06 20:11:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") PnStat record, @Param("example") PnStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_020_pn_stat
     *
     * @mbggenerated Mon Feb 06 20:11:27 CST 2017
     */
    int updateByExample(@Param("record") PnStat record, @Param("example") PnStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_020_pn_stat
     *
     * @mbggenerated Mon Feb 06 20:11:27 CST 2017
     */
    int updateByPrimaryKeySelective(PnStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_020_pn_stat
     *
     * @mbggenerated Mon Feb 06 20:11:27 CST 2017
     */
    int updateByPrimaryKey(PnStat record);
}